#!/bin/sh

set -e

# Automatically added by dh_installinit/11.2.1
if [ -e /etc/cron.daily/btrfs-tools-snapshots ]; then
  rm -f /etc/cron.daily/btrfs-tools-snapshots
fi
if [ -e /etc/cron.weekly/btrfs-tools-snapshots ]; then
  rm -f /etc/cron.weekly/btrfs-tools-snapshots
fi
if [ -e /etc/apt/apt.conf.d/80btrfs-tools-snapshots ]; then
  rm -f /etc/apt/apt.conf.d/80btrfs-tools-snapshots
fi
# End automatically added section
