#!/bin/sh

set -e

case "$1" in
remove|purge)
  if [ -e /etc/cron.daily/btrfs-tools-snapshots ]; then
    rm -f /etc/cron.daily/btrfs-tools-snapshots
  fi
  if [ -e /etc/cron.weekly/btrfs-tools-snapshots ]; then
    rm -f /etc/cron.weekly/btrfs-tools-snapshots
  fi
  if [ -e /etc/apt/apt.conf.d/80btrfs-tools-snapshots ]; then
    rm -f /etc/apt/apt.conf.d/80btrfs-tools-snapshots
  fi
esac
